### ISSUE TITLE
Error message on ChatToSpeech.exe

### ISSUE THREAD

**Issue by wbrandon25** [Joey-Einerhand/TF2ChatToSpeech#1]
![image](https://user-images.githubusercontent.com/73367549/97057239-a6c54080-153f-11eb-946c-2be694a94b83.png)
Getting this error message in the picture. I did the easy method of installation and I think I did everything correctly. The error occurs when anyone says something in chat. Do you know what could be causing the problem?

**Comment by Joey-Einerhand** [comment]
Hey there. Could you try to install [this](https://www.microsoft.com/en-us/download/details.aspx?id=27224) and check if that solves the issue?

Could you also tell me what version of Windows you're running? Open windows explorer, right click on "This pc" and click on "properties". There should be a category called 'system' with a 'System type' specification. It should say something like 64-bits or 32-bits. Which one do you have?

**Comment by wbrandon25** [comment]
I assume I only need to install the first one? I still get the same problem when trying to use it. 
I have a 64 bit system.

**Comment by Joey-Einerhand** [comment]
Just to confirm- what operating system are you on?

I've attached a .zip to this comment, could you try installing it? (Don't install the settings folder in the zip if you want to keep your saved settings)
[TF2ChatToSpeech_V1.1.zip](https://github.com/Joey-Einerhand/TF2ChatToSpeech/files/5445217/TF2ChatToSpeech_V1.1.zip)

Please tell me if this fixes/doesn't fix the issue.

**Comment by wbrandon25** [comment]
I'm on windows 10. I tried using the files in the new zip, but i'm still getting the same error.

**Comment by Joey-Einerhand** [comment]
Okay- Let's see if your system has any voices installed.
Go to your windows start menu and search for 'regedit'
Open it, and navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Speech\Voices\Tokens.
It should look something like this : 
![image](https://user-images.githubusercontent.com/19751158/97410092-e81e6d00-18fe-11eb-9bc5-71e4f6174595.png)

Does the Tokens map contain any voices (TTS_MS files)? If so, which?

**Comment by wbrandon25** [comment]
![image](https://user-images.githubusercontent.com/73367549/97460116-b6ef6e00-18f9-11eb-9cbc-ea6756effc34.png)
I have these 2

**Comment by Joey-Einerhand** [comment]
Thanks. The issue lies with how I coded TF2Chat To Speech. I'll try to find the time to fix it by the end of this week.

If you _really really_ want the program to run _right now_, you could download the English (Great Britain) voice by following these instructions: https://support.microsoft.com/en-us/office/how-to-download-text-to-speech-languages-for-windows-10-d5a6b612-b3ae-423f-afa5-4f6caf1ec5d3

**Comment by Joey-Einerhand** [comment]
Should be fixed now. Feel free to download V1.2.

Thanks for bringing the bug to my attention :D
